name: new_horizon_challenge_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-FD-Bold.ttf
          weight: 600
